# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'System Utilities' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for System Utilities

#pod 'Google-Mobile-Ads-SDK'
pod 'Flurry-iOS-SDK'
pod 'Charts'
pod 'iRate'
pod 'SVProgressHUD'

end
